/*
 * App URI: sample-map
 * Source Location: sample-map.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5949), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("sample-map", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * sample-map.js
			 * Created at 2025. 12. 22. 오전 11:32:26.
			 *
			 * @author LCM
			 ************************************************/;
			// End - User Script
			
			// Header
			var submission_1 = new cpr.protocols.Submission("sms1");
			submission_1.method = "get";
			submission_1.action = "../api/map/sido.do";
			if(typeof onSms1Receive == "function") {
				submission_1.addEventListener("receive", onSms1Receive);
			}
			app.register(submission_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.horizontalSpacing = "10px";
			formLayout_1.verticalSpacing = "10px";
			formLayout_1.topMargin = "5px";
			formLayout_1.rightMargin = "5px";
			formLayout_1.bottomMargin = "5px";
			formLayout_1.leftMargin = "5px";
			formLayout_1.setColumns(["1fr"]);
			formLayout_1.setRows(["1fr"]);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var userDefinedControl_1 = new udc.udcMapEx();
			container.addChild(userDefinedControl_1, {
				"colIndex": 0,
				"rowIndex": 0
			});
		}
	});
	app.title = "sample-map";
	cpr.core.Platform.INSTANCE.register(app);
})();
